### ISSUE TITLE
Support multiline message

### ISSUE THREAD

**Issue by notok** [matsukaz/hubot-schedule#10]
Currently, scheduling multiline message is not supported.

I think multiline message is sometimes useful.
For example, like this

```
hubot schedule add "2016-05-11 10:25" MEETING will start in 5 minutes.
Location: Meeting room 155
Attendees: @Sato, @Tanaka, ...
Note: **Do NOT forget to bring the text.**
```

multiline message can be achieved like following.

https://github.com/notok/hubot-schedule/tree/support_multiline

If you'd like to make it an option, see this.

https://github.com/notok/hubot-schedule/tree/support_multiline_optional

Please tell me if you want a PR.

**Comment by matsukaz** [comment]
Thank you for your issue and it sounds great!
I think most people want to use multiline, so `support_multiline` branch is fine.
Please send me a PR and I'll merge it :)

**Comment by notok** [comment]
@matsukaz Thank you for your comment.
I sent the PR( #11 ). Please check and merge it.
