### ISSUE TITLE
need to support hubot-slack v4.x

### ISSUE THREAD

**Issue by matsukaz** [matsukaz/hubot-schedule#14]
According to the [document](https://slackapi.github.io/hubot-slack/upgrading), we need to fix the code in order to handle room name instead of room identifier when using hubot-slack v4.

**Comment by chriskol** [comment]
Was this done?  I seem to be able to post to any of my channels using the channel name EXCEPT general.  Actually except for a few channels...but some channels work...I wonder if it's dependent on when the channels were created?

**Comment by matsukaz** [comment]
No, not yet. sorry...
I don't know if this will fix your problem, but I'll try to support hubot-slack v4 in next few days.

**Comment by matsukaz** [comment]
hubot-schedule now supports hubot-slack v4.
sorry for my late response.

**Comment by matsukaz** [comment]
@chriskol I've fixed this problem and released as v0.6.1.
plz try it :)

**Comment by chriskol** [comment]
It's still only working for some channels.  Looks like channels that were created after a certain date but I'm not sure as to the logic behind it. My hubot is in these channels as well.

**Comment by chriskol** [comment]
@matsukaz It's still only working for some channels. Looks like channels that were created after a certain date but I'm not sure as to the logic behind it. My hubot is in these channels as well.

**Comment by matsukaz** [comment]
@chriskol Is it possible to recreate schedules?
This fix only works for newly created schedules, sorry X(

It is possible to support existent schedules, but needed to check channel's name each time to do so and this might affect performance,so I didn't implement this...
If you have lots of schedules and hard to recreate all,plz let me know. I'll think about other solutions.

**Comment by chriskol** [comment]
@matsukaz This was for a new schedule I created.  I have no schedules and tested on an item that was like 10minutes ahead of time.  It didn't even give a schedule creation response.  I tried for a different channel and it gave a scheduled item created response.  Not sure why some channels are working but others are not.

Check out this screenshot https://www.dropbox.com/s/x6w9l3gx8rjat3l/Screenshot%202017-06-13%2012.52.13.png?dl=0

**Comment by matsukaz** [comment]
@chriskol Which version of `hubot-slack` are you using?
When I changed my `hubot-slack` version from `4.3.4` to `4.2.1`, same thing happened...
If you are using old version of `hubot-slack`, is it possible to update to the recent version `4.3.4` ?

If it still occurs, could you send me your `npm list` to see each node packages version ?

**Comment by chriskol** [comment]
It's working now actually!  I was running an old verison of hubot-slack d'oh.  Wasn't working at first but it's working now!

**Comment by matsukaz** [comment]
I'm glad it worked!
I'll write down `hubot-slack` version to README.md so that other people will not face to the same problem.
Thank you for using my library 😄
