### ISSUE TITLE
Where hubot-schedule store data of schedule tasks?

### ISSUE THREAD

**Issue by arpsyapathy** [matsukaz/hubot-schedule#16]
Hi all!

Where hubot-schedule store data of schedule tasks?

When i docker-compose down i loose my schedule tasks(
How fit it?

**Comment by matsukaz** [comment]
@arpsyapathy 
hubot-schedule uses robot.brain to store it's data.
As described in the hubot official document, robot.brain runs as in-memory key-value store as default.

> Hubot has an in-memory key-value store exposed as robot.brain that can be used to store and retrieve data by scripts.

you can change the storage to Redis, MySQL, PostgreSQL and more by using external libraries like follows.

https://github.com/hubotio/hubot-redis-brain
https://github.com/chickenzord/hubot-mysql-brain
https://github.com/changhaitravis/hubot-postgres-brain
https://github.com/shokai/hubot-mongodb-brain

**Comment by matsukaz** [comment]
Hope my reply solved your issue.
If you have any other questions, please reopen this issue or create new issue.
