### ISSUE TITLE
What timezone?

### ISSUE THREAD

**Issue by MrMMorris** [matsukaz/hubot-schedule#3]
Thanks for the awesome plugin!

I was wondering what timezone does cron follow? Is it the timezone of the server hubot is running on? or UTC?

It would be cool to be able tot set a timezone with an env var or something :)

**Comment by matsukaz** [comment]
Thanks for your comment :)

This plugin doesn't handle any timezone, so as you mentioned, the cron follows on the server time settings.

I was also thinking of supporting timezone, but the "node-schedule" I'm using doesn't support it, so it's quite hard to do so.

May be I should use "node-cron" instead, which act like "cron-parser" and also supports timezone.
Anyway, I'll try to support timezone in next few days.

**Comment by MrMMorris** [comment]
@matsukaz no worries on the timezones. My servers are in UTC anyways so it's not hard to adjust. Probably more work than it's worth.

I should note, however, that there is some weirdness with the script.

It seems I can create schedules and they work fine, but when I delete them, even though it doesn't run anymore and is gone in Redis, they all still show up with `hubot schedule list`

```
$ Hubot schedule list
Message is not scheduled

$ Hubot schedule new "1 1 * * 1-4" blah
8085: Schedule created

$ Hubot schedule list
8085: [ 1 1 * * 1-4 ] #test blah

$ Hubot schedule remove 8085
8085: Schedule cancelled

$ Hubot schedule list 
8085: [ 1 1 * * 1-4 ] #test blah
```

Not sure if it's being cached or something.

**Comment by matsukaz** [comment]
Humm, that's weird...
I'll try to fix that first, and than think about timezone later.

**Comment by matsukaz** [comment]
@MrMMorris 
I've just fixed the bug you have mentioned and bumped version to 0.2.1. Thanks for your report!

**Comment by MrMMorris** [comment]
you're amazing!
